package me.tbsten.cream.ksp.core.callFrom

import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSDeclaration
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.google.devtools.ksp.symbol.KSTypeParameter
import com.google.devtools.ksp.symbol.Modifier
import me.tbsten.cream.ksp.core.common.CopyFunctionTypeParameters
import me.tbsten.cream.ksp.core.common.GenerateSourceAnnotation
import me.tbsten.cream.ksp.core.common.appendAutoGeneratedFunctionKDoc
import me.tbsten.cream.ksp.core.common.appendExample
import me.tbsten.cream.ksp.core.common.appendTypeParameterList
import me.tbsten.cream.ksp.core.common.appendWhereClause
import me.tbsten.cream.ksp.core.common.deprecatedAnnotationLineOfDeclarations
import me.tbsten.cream.ksp.core.common.fullName
import me.tbsten.cream.ksp.core.common.getCopyFunctionTypeParameters
import me.tbsten.cream.ksp.core.common.underPackageName
import me.tbsten.cream.ksp.core.common.warnIfTargetExcludeHasNoEffect
import me.tbsten.cream.ksp.options.CreamOptions
import me.tbsten.cream.ksp.util.escapeDottedKotlinIdentifier
import me.tbsten.cream.ksp.util.escapeKotlinIdentifier
import me.tbsten.cream.ksp.util.ksp.asString
import me.tbsten.cream.ksp.util.safeCast

/**
 * Append the bridge overload that calls [targetFunction] from a [source] argument-holder object.
 *
 * ```kt
 * public fun processData(
 *     processDataArgs: ProcessDataArgs,
 *     data1: String = processDataArgs.data1,
 *     data2: Int = processDataArgs.data2,
 * ): Unit = processData(
 *     data1 = data1,
 *     data2 = data2,
 * )
 * ```
 *
 * - A member function is bridged as a top-level extension function on its enclosing class
 *   (`fun Enclosing.processData(...)`), because KSP cannot add members to an existing class.
 * - An extension function is bridged as an extension function on the same receiver
 *   (`fun Receiver.processData(...)`), which forwards to the original through the implicit
 *   receiver.
 * - The body passes the *parameters* (`data1 = data1`), never the source properties, so
 *   caller-side overrides always win over the auto-copied defaults.
 * - An unmatched parameter with a default value on the original function is omitted from both
 *   the bridge signature and the forwarding call, so the original default applies
 *   (see [CallFromBridgeParameter]).
 * - `suspend` is transcribed; `operator` / `infix` / `inline` / `tailrec` are deliberately NOT:
 *   the bridge's shape (an extra leading parameter) no longer satisfies the operator/infix
 *   conventions, and the bridge is an ordinary call site of the original, so `inline` / `tailrec`
 *   still take effect inside the original function.
 * - `@Deprecated` on the annotated function / enclosing class / source class / matched source
 *   properties is propagated onto the bridge so the generated references compile warning-free.
 *   `ERROR` / `HIDDEN` deprecation of any of them is rejected by the feature layer — the bridge
 *   could not reference them.
 *
 * [visibilityModifier] is computed (and validated against the source / enclosing-class
 * visibility) by the feature layer.
 *
 * The feature layer has already rejected unsupported function kinds (private / protected /
 * local / abstract / expect / member extension / member of a generic class), so this generator
 * assumes a callable, non-generic-enclosed function.
 */
context(options: CreamOptions, logger: KSPLogger)
internal fun Appendable.appendCallFromFunction(
    source: KSClassDeclaration,
    targetFunction: KSFunctionDeclaration,
    omitPackages: List<String>,
    visibilityModifier: String,
    generateSourceAnnotation: GenerateSourceAnnotation.CallFrom,
) {
    // `funName` names the bridge *declaration* (a custom name, or the target's name by default);
    // `delegateName` is always the original function's own name, which the bridge body forwards to
    // — for a custom `funName` these differ, so the bridge must not call itself.
    val funName = resolveCallFromFunName(generateSourceAnnotation.funNameTemplate, targetFunction).escapeKotlinIdentifier()
    val delegateName = targetFunction.simpleName.asString().escapeKotlinIdentifier()
    val sourceParamName = callFromSourceParamName(source)
    val enclosingClass = targetFunction.parentDeclaration.safeCast<KSClassDeclaration>()
    val typeParameters =
        getCopyFunctionTypeParameters(
            sourceClass = source,
            targetConstructor = targetFunction,
        )
    val typeParameterToString: (KSType) -> String =
        { typeParameters.resolveTypeParameterName(it.declaration) }
    val bridgeParameters = callFromBridgeParameters(source, targetFunction, generateSourceAnnotation)
    val receiver =
        enclosingClass?.fullName?.escapeDottedKotlinIdentifier()
            ?: targetFunction.extensionReceiver
                ?.resolve()
                ?.asString(omitPackages = omitPackages, typeParameterToString = typeParameterToString)

    appendCallFromKDoc(
        source = source,
        targetFunction = targetFunction,
        generateSourceAnnotation = generateSourceAnnotation,
        funName = funName,
        sourceParamName = sourceParamName,
        requiredParamNames =
            bridgeParameters
                .filter { it.isKept && !it.hasAutoDefault }
                .map { it.parameter.name!!.asString() },
        receiverDeclaration = enclosingClass ?: targetFunction.extensionReceiver?.resolve()?.declaration,
    )

    // Propagate @Deprecated from every symbol the bridge actually references: the called
    // function, the receiver's class, the source class, and the matched properties the defaults
    // read. Unmatched source properties are deliberately NOT scanned (unlike the copy features'
    // deprecatedAnnotationLine) — the bridge never touches them, so their deprecation must not
    // deprecate the bridge.
    val deprecatedLine =
        deprecatedAnnotationLineOfDeclarations(
            listOfNotNull(targetFunction, enclosingClass, source) +
                bridgeParameters.filter { it.hasAutoDefault }.mapNotNull { it.matchedProperty },
        )
    deprecatedLine?.let { appendLine(it) }

    append(visibilityModifier)
    append(" ")
    if (Modifier.SUSPEND in targetFunction.modifiers) append("suspend ")
    append("fun ")
    appendTypeParameterList(typeParameters, omitPackages)
    if (typeParameters.isNotEmpty()) append(" ")
    receiver?.let { append("$it.") }
    append("$funName(")
    appendLine()

    append("    $sourceParamName: ")
    appendSourceTypeWithArgs(source, typeParameters, omitPackages)
    append(",\n")

    bridgeParameters.forEach { bridgeParameter ->
        val parameter = bridgeParameter.parameter
        parameter.warnIfTargetExcludeHasNoEffect(bridgeParameter.matchedProperty, generateSourceAnnotation, logger)
        if (!bridgeParameter.isKept) return@forEach

        val paramName = parameter.name!!.asString()
        val paramType =
            parameter.type
                .resolve()
                .asString(
                    omitPackages = omitPackages,
                    typeParameterToString = typeParameterToString,
                )
        val modifiers = if (parameter.isVararg) "vararg " else ""
        append("    $modifiers${paramName.escapeKotlinIdentifier()}: $paramType")

        if (bridgeParameter.hasAutoDefault) {
            val propertyName =
                bridgeParameter.matchedProperty!!
                    .simpleName
                    .asString()
                    .escapeKotlinIdentifier()
            append(" = $sourceParamName.$propertyName")
        }
        append(",\n")
    }
    append("): ")
    append(
        targetFunction.returnType
            ?.resolve()
            ?.asString(
                omitPackages = omitPackages,
                typeParameterToString = typeParameterToString,
            ) ?: "Unit",
    )
    appendWhereClause(typeParameters, omitPackages)
    append(" = $delegateName(")
    appendLine()
    bridgeParameters.filter { it.isKept }.forEach { bridgeParameter ->
        val escaped =
            bridgeParameter.parameter.name!!
                .asString()
                .escapeKotlinIdentifier()
        // A vararg parameter is also forwarded as `name = name`: assigning the bridge's own
        // vararg (an array) to the original vararg in named form passes it through as-is.
        // Do not add a spread — kotlinc flags `name = *name` as "Redundant spread (*) operator".
        appendLine("    $escaped = $escaped,")
    }
    appendLine(")")
    appendLine()
}

/**
 * Resolve a type-parameter reference appearing in a parameter / return / receiver type to the
 * generated function's own type-parameter name, falling back to the declaration's simple name.
 * Unlike `resolveConstructorParamTypeParameter`, this never throws: `@CallFrom` has no target
 * *class* to blame in an error message, and an unmatched name is still valid output.
 */
private fun CopyFunctionTypeParameters.resolveTypeParameterName(declaration: KSDeclaration): String {
    val typeParameter =
        declaration.safeCast<KSTypeParameter>()
            ?: return declaration.simpleName.asString()
    return getNameFromTargetConstructorTypeParameters(typeParameter)
        ?: getNameFromSourceClassTypeParameters(typeParameter)
        ?: typeParameter.name.asString()
}

/**
 * Append the source (argument-holder) type with its type arguments resolved through
 * [typeParameters], e.g. `com.example.Args<T>`. Unlike the receiver position of copy
 * functions, this is a *parameter* type, so packages in [omitPackages] are stripped the
 * same way as the other parameter types.
 */
private fun Appendable.appendSourceTypeWithArgs(
    source: KSClassDeclaration,
    typeParameters: CopyFunctionTypeParameters,
    omitPackages: List<String>,
) {
    append(
        (if (source.packageName.asString() in omitPackages) source.underPackageName else source.fullName)
            .escapeDottedKotlinIdentifier(),
    )
    if (source.typeParameters.isEmpty()) return
    append("<")
    append(
        source.typeParameters.joinToString(", ") { typeParam ->
            typeParameters.getNameFromSourceClassTypeParameters(typeParam)
                ?: typeParam.name.asString()
        },
    )
    append(">")
}

private fun Appendable.appendCallFromKDoc(
    source: KSClassDeclaration,
    targetFunction: KSFunctionDeclaration,
    generateSourceAnnotation: GenerateSourceAnnotation,
    funName: String,
    sourceParamName: String,
    requiredParamNames: List<String>,
    receiverDeclaration: KSDeclaration?,
) {
    val receiverPrefix =
        receiverDeclaration
            ?.simpleName
            ?.asString()
            ?.replaceFirstChar { it.lowercaseChar() }
            ?.let { "${it.escapeKotlinIdentifier()}." }
            ?: ""
    // Required parameters are rendered as `name = ...`: the right-hand side is a placeholder the
    // caller fills in, not a variable defined in the example (which `name = name` looked like).
    val requiredArgs = requiredParamNames.joinToString(", ") { "$it = ..." }
    val basicCall =
        if (requiredArgs.isEmpty()) sourceParamName else "$sourceParamName, $requiredArgs"
    val overrideCall =
        if (requiredArgs.isEmpty()) {
            "$sourceParamName, parameter = value"
        } else {
            "$sourceParamName, $requiredArgs, parameter = value"
        }
    appendAutoGeneratedFunctionKDoc(
        generateSourceAnnotation = generateSourceAnnotation,
        seeClasses = listOf(source),
        autoDescription = {
            appendLine("${source.underPackageName} -> ${targetFunction.underPackageName}() bridge function.")
        },
        autoExamples = {
            appendExample(
                "Example: Basic",
                """
                val $sourceParamName = ${source.underPackageName}(...)
                $receiverPrefix$funName($basicCall)
                """.trimIndent(),
            )

            appendExample(
                "Example: Override parameter values",
                """
                val $sourceParamName = ${source.underPackageName}(...)
                $receiverPrefix$funName($overrideCall)
                """.trimIndent(),
            )
        },
    )
}
