package me.tbsten.cream.ksp.core.parentOptional

import com.google.devtools.ksp.processing.KSPLogger
import me.tbsten.cream.ksp.core.common.appendAutoGeneratedFunctionKDoc
import me.tbsten.cream.ksp.core.common.appendExample
import me.tbsten.cream.ksp.core.common.deprecatedAnnotationOrNull
import me.tbsten.cream.ksp.core.common.renderSealedReceiverType
import me.tbsten.cream.ksp.core.common.renderTypeParameterList
import me.tbsten.cream.ksp.core.common.renderWhenBranchType
import me.tbsten.cream.ksp.core.common.renderWhereClause
import me.tbsten.cream.ksp.core.common.toAnnotationLine
import me.tbsten.cream.ksp.core.common.underPackageName
import me.tbsten.cream.ksp.options.CreamOptions
import me.tbsten.cream.ksp.util.escapeKotlinIdentifier

/**
 * Append one nullable extension property on the sealed parent, dispatching to each merged
 * child property (see [ParentOptionalAccessorSpec]):
 *
 * ```kt
 * public val MyState.data: String?
 *     get() = when (this) {
 *         is MyState.Success -> data
 *         else -> null
 *     }
 * ```
 *
 * Validation lives in [validatedPropertyTypeTextOrNull] and [validatedVisibilityModifierOrNull];
 * when either reports an error this appends nothing (the shared transactional output buffer then
 * skips the accessor while sibling accessors of the same parent still generate). A property whose
 * type is already nullable keeps its type as-is — the `?` is never doubled.
 */
context(options: CreamOptions, logger: KSPLogger)
internal fun Appendable.appendParentOptionalAccessor(
    spec: ParentOptionalAccessorSpec,
    omitPackages: List<String>,
) {
    // Subtype-related children must dispatch most-derived-first or the parent's `is` branch
    // would shadow the child's (see withEntriesMostDerivedFirst).
    val orderedSpec = spec.withEntriesMostDerivedFirst()
    val propertyTypeText = orderedSpec.validatedPropertyTypeTextOrNull(omitPackages) ?: return
    val visibilityModifier = orderedSpec.validatedVisibilityModifierOrNull() ?: return
    val accessorTypeText = if (orderedSpec.isPropertyTypeNullable) propertyTypeText else "$propertyTypeText?"

    appendParentOptionalKDoc(orderedSpec, accessorTypeText)

    // The generated getter references each merged child class and property; when any of them is
    // @Deprecated, the annotation is propagated so accessor *callers* keep seeing the deprecation
    // (issue #103 precedent — see deprecatedAnnotationLineOrNull). Unlike a deprecated function's
    // body, a property accessor's body is NOT exempted from deprecation reporting by containment,
    // so the getter's own references additionally need DEPRECATION(_ERROR) suppressed — without
    // it a DeprecationLevel.ERROR source would fail to compile.
    val deprecatedLine = orderedSpec.deprecatedAnnotationLineOrNull()
    deprecatedLine?.let(::appendLine)
    // REDUNDANT_ELSE_IN_WHEN: when every subtype of the parent contributes a branch the `when`
    // becomes exhaustive and the user's build would warn "'when' is exhaustive so 'else' is
    // redundant here".
    if (deprecatedLine != null) {
        appendLine("@Suppress(\"REDUNDANT_ELSE_IN_WHEN\", \"DEPRECATION\", \"DEPRECATION_ERROR\")")
    } else {
        appendLine("@Suppress(\"REDUNDANT_ELSE_IN_WHEN\")")
    }
    append(visibilityModifier)
    append(" val ")
    append(renderTypeParameterList(orderedSpec.parent.typeParameters, omitPackages))
    if (orderedSpec.parent.typeParameters.isNotEmpty()) append(" ")
    append(renderSealedReceiverType(orderedSpec.parent, omitPackages))
    append(".")
    append(orderedSpec.accessorName.escapeKotlinIdentifier())
    append(": ")
    append(accessorTypeText)
    append(renderWhereClause(orderedSpec.parent.typeParameters, omitPackages))
    appendLine()
    appendLine("    get() = when (this) {")
    orderedSpec.entries.forEach { entry ->
        val branchType = renderWhenBranchType(entry.child, orderedSpec.parent)
        val propertyName =
            entry.property.simpleName
                .asString()
                .escapeKotlinIdentifier()
        appendLine("        is $branchType -> $propertyName")
    }
    appendLine("        else -> null")
    appendLine("    }")
    appendLine()
}

private fun Appendable.appendParentOptionalKDoc(
    spec: ParentOptionalAccessorSpec,
    accessorTypeText: String,
) {
    // underPackageName (not the simple name): a nested parent's KDoc link / example must be
    // qualified relative to the package (`Root.Middle`) or the reference does not resolve.
    val parentName = spec.parent.underPackageName
    // Link the underlying child properties, not `accessorName`: the accessor name is the
    // *generated* extension's name and can differ from the child property names
    // (`propertyName = ...`, merged contributions), so the children may declare no such property.
    val propertyRefs = spec.entries.joinToString(" / ") { "[${it.property.underPackageName}]" }
    val escapedAccessorName = spec.accessorName.escapeKotlinIdentifier()
    appendAutoGeneratedFunctionKDoc(
        generateSourceAnnotation = spec.entries.first().sourceAnnotation,
        seeClasses = listOf(spec.parent) + spec.entries.map { it.property },
        autoDescription = {
            appendLine("Nullable accessor on [$parentName] exposing $propertyRefs.")
            appendLine()
            appendLine("Returns the property value when `this` is such a child, otherwise `null`.")
            if (spec.isPropertyTypeNullable) {
                appendLine()
                appendLine(
                    "Note: the property type is itself nullable, so `null` is ambiguous here — " +
                        "it can mean \"the receiver is not such a child\" or the property's own `null` value. " +
                        "Use an `is` check when the distinction matters.",
                )
            }
        },
        autoExamples = {
            appendExample(
                "Example",
                """
                val state: $parentName = /* one of the subtypes */
                val $escapedAccessorName: $accessorTypeText = state.$escapedAccessorName
                """.trimIndent(),
            )
        },
    )
}

/**
 * The `@Deprecated(...)` line to propagate onto this accessor, or `null` when no merged entry is
 * deprecated. The first deprecation found wins, scanning entries in the emitted (`is`-branch)
 * order and, within each entry, checking the child's class-level `@Deprecated` before the
 * property's own (mirroring [deprecatedAnnotationLine] for copy functions). The
 * primary-constructor parameter is checked as a fallback for the property, for the same
 * KSP2-surfacing reason as [parentOptionalAnnotationOrNull].
 */
private fun ParentOptionalAccessorSpec.deprecatedAnnotationLineOrNull(): String? =
    entries
        .firstNotNullOfOrNull { entry ->
            entry.child.deprecatedAnnotationOrNull()
                ?: entry.property.deprecatedAnnotationOrNull()
                ?: entry.property
                    .correspondingConstructorParameter()
                    ?.deprecatedAnnotationOrNull()
        }?.toAnnotationLine()
