package me.tbsten.cream

/**
 * Generate copy functions from a sealed type down to its concrete leaves, each one
 * returning the **specific leaf** (i.e. a type-narrowing transition). For a flat sealed
 * type these are its direct children; for nested hierarchies the generation recurses
 * through any intermediate sealed *types* (not just the direct children).
 *
 * # Example
 *
 * ```kt
 * @CopyToChildren
 * sealed interface UiState {
 *   val sessionId: String
 *   data class Loading(override val sessionId: String) : UiState
 *   data class Success(override val sessionId: String, val data: String) : UiState
 * }
 *
 * // Auto generate
 *
 * fun UiState.copyToUiStateLoading(
 *   sessionId: String = this.sessionId,
 * ): UiState.Loading = /* ... */
 *
 * fun UiState.copyToUiStateSuccess(
 *   sessionId: String = this.sessionId,
 *   data: String,
 * ): UiState.Success = /* ... */
 * ```
 *
 * # Difference from [SealedCopy]
 *
 * `@SealedCopy` generates a single type-preserving extension on the sealed parent
 * (`UiState.copy(...): UiState`) that dispatches to each subtype's own `copy`. Use
 * it when you want to update shared properties without changing the concrete subtype.
 *
 * `@CopyToChildren` generates per-child copy functions whose return type is the
 * child (`UiState.copyToUiStateLoading(...): UiState.Loading`) — a type-narrowing
 * transition. Use it when you are explicitly transitioning between subtypes (e.g.
 * `Loading → Success`).
 *
 * Both annotations may coexist on the same sealed type when both shapes are useful.
 *
 * # Map
 *
 * Annotate a **property declared on the sealed parent** with [CopyToChildren.Map] to bind it to
 * differently-named constructor parameters of the children. The mapped parameter receives the
 * `= this.<property>` auto-copy default even though the names differ. This affects only the
 * `@CopyToChildren`-generated functions. See [CopyToChildren.Map] for details and an example.
 *
 * # Exclude
 *
 * Annotate a **property declared on the sealed parent** with [CopyToChildren.Exclude] to drop its
 * `= this.<property>` auto-copy default. The matching parameter becomes required at the call site
 * across **all** per-child copy functions. This affects only the `@CopyToChildren`-generated
 * functions and not any `@SealedCopy`-generated `copy()`. See [CopyToChildren.Exclude] for details
 * and an example.
 *
 * @property notCopyToObject When `true`, skip generating copy functions whose target
 *   child is an `object` (those would just return the singleton). Defaults to `false`.
 * @property visibility Visibility modifier applied to every generated per-child copy
 *   function. Defaults to [CopyVisibility.INHERIT], which keeps cream's existing behaviour
 *   (each function inherits its target child's visibility).
 * @property funName Template for the generated function names. Defaults to
 *   [DefaultCopyFunctionName] (cream's derived name). `@CopyToChildren` fans out to **every**
 *   concrete leaf of the sealed hierarchy, so it usually generates more than one function — embed
 *   a per-target token such as [CopyTargetSimpleName] so each leaf gets a distinct name, e.g.
 *   `funName = "to" + CopyTargetSimpleName`. A plain literal (no token) would make every per-leaf
 *   function share one name and collide, so it is rejected with a compilation error whenever more
 *   than one function is generated. See `CopyFunctionNameToken.kt`.
 *
 * @see SealedCopy
 * @see CopyTo
 * @see CopyToChildren.Map
 * @see CopyToChildren.Exclude
 * @see CopyVisibility
 * @see DefaultCopyFunctionName
 */
@Target(AnnotationTarget.CLASS)
public annotation class CopyToChildren(
    val notCopyToObject: Boolean = false,
    val kdoc: KDoc = KDoc(),
    val visibility: CopyVisibility = CopyVisibility.INHERIT,
    val funName: String = DefaultCopyFunctionName,
) {
    /**
     * Bind a **property declared on the sealed parent** to differently-named constructor
     * parameters of the children (**name mapping**), across **all** `@CopyToChildren`-generated
     * per-child copy functions.
     *
     * Place this annotation on a property declared on the sealed parent and list the child-side
     * constructor parameter name(s) it should supply. In every generated `copyTo<Child>(...)`
     * function, a parameter whose name appears in [propertyNames] receives the
     * `= this.<property>` auto-copy default even though the names differ. The mapping takes
     * precedence over plain name matching. Because `@CopyToChildren` fans out to every concrete
     * leaf, [propertyNames] is a `vararg` — list one name per child-side spelling when the
     * children disagree on the parameter name.
     *
     * This mirrors `@CopyTo.Map` / `@CopyFrom.Map` and the other annotations' `.Map`. Like
     * [CopyToChildren.Exclude], it only affects the `@CopyToChildren`-generated per-child
     * functions and does **not** affect functions generated by other cream annotations on the
     * same sealed type. Combining it with [CopyToChildren.Exclude] on the same property drops the
     * mapped parameter's auto-copy default, making it required. A name in [propertyNames] that
     * matches no child constructor parameter simply has no effect (that child's parameters keep
     * their usual matching).
     *
     * # Example
     *
     * ```kt
     * @CopyToChildren
     * sealed interface UiState {
     *   @CopyToChildren.Map("id")
     *   val sessionId: String
     *
     *   data class Loading(val id: String) : UiState {
     *     override val sessionId: String get() = id
     *   }
     *   data class Success(val id: String, val data: String) : UiState {
     *     override val sessionId: String get() = id
     *   }
     * }
     *
     * // Generated:
     * fun UiState.copyToUiStateLoading(
     *   id: String = this.sessionId,   // sessionId is mapped to id
     * ): UiState.Loading = /* ... */
     *
     * fun UiState.copyToUiStateSuccess(
     *   id: String = this.sessionId,   // sessionId is mapped to id
     *   data: String,
     * ): UiState.Success = /* ... */
     * ```
     *
     * @property propertyNames The child-side constructor parameter name(s) this sealed-parent
     *   property maps to.
     * @see CopyToChildren
     * @see CopyToChildren.Exclude
     * @see CopyTo.Map
     */
    @Target(AnnotationTarget.PROPERTY)
    public annotation class Map(
        vararg val propertyNames: String,
    )

    /**
     * Remove the auto-copy default from a sealed parent's property across **all**
     * `@CopyToChildren`-generated per-child copy functions, making the corresponding
     * parameter required in every generated function.
     *
     * Place this annotation on a **property declared on the sealed parent**. The
     * corresponding parameter in every generated `copyTo<Child>(...)` function loses the
     * `= this.<property>` default, forcing the caller to supply an explicit value regardless
     * of which child type they are transitioning to.
     *
     * This annotation only affects the `@CopyToChildren`-generated per-child functions and
     * does **not** affect any `@SealedCopy`-generated `copy()` on the same sealed type.
     *
     * Applying `@CopyToChildren.Exclude` to a property that does not appear in any
     * generated per-child function's parameter list has no effect and emits a KSP warning.
     *
     * # Example
     *
     * ```kt
     * @CopyToChildren
     * sealed interface UiState {
     *   val sessionId: String
     *   @CopyToChildren.Exclude val count: Int  // caller must specify count explicitly
     *   data class Loading(override val sessionId: String, override val count: Int) : UiState
     *   data class Success(override val sessionId: String, override val count: Int, val data: String) : UiState
     * }
     *
     * // Generated:
     * fun UiState.copyToUiStateLoading(
     *   sessionId: String = this.sessionId,
     *   count: Int,                             // no default — required
     * ): UiState.Loading = /* ... */
     *
     * fun UiState.copyToUiStateSuccess(
     *   sessionId: String = this.sessionId,
     *   count: Int,                             // no default — required
     *   data: String,
     * ): UiState.Success = /* ... */
     * ```
     *
     * @see CopyToChildren
     * @see CopyToChildren.Map
     * @see SealedCopy.Exclude
     */
    @Target(AnnotationTarget.PROPERTY)
    public annotation class Exclude
}
