package me.tbsten.cream

/**
 * Expose one sealed child's property on the sealed parent type as a **nullable extension
 * property**. The generated accessor returns the property's value when the receiver is the
 * annotated child, or `null` otherwise — replacing the `(state as? Success)?.data`
 * boilerplate that piles up around UI state (MVI / UiState) code.
 *
 * # Example
 *
 * ```kt
 * sealed interface MyState {
 *   data class Success(@ParentOptional val data: String) : MyState
 *   data object Loading : MyState
 * }
 *
 * // Auto generate
 *
 * public val MyState.data: String?
 *   get() = when (this) {
 *     is MyState.Success -> data
 *     else -> null
 *   }
 * ```
 *
 * # Merging across children
 *
 * When properties of **multiple** children resolve to the same generated name on the same
 * sealed parent, they are merged into a single accessor with one `is` branch per child.
 * All merged properties must have the same type (a type mismatch is a compilation error).
 *
 * ```kt
 * sealed interface MyState {
 *   data class Success(@ParentOptional val message: String) : MyState
 *   data class Failure(@ParentOptional val message: String) : MyState
 *   data object Loading : MyState
 * }
 *
 * // Auto generate
 *
 * public val MyState.message: String?
 *   get() = when (this) {
 *     is MyState.Success -> message
 *     is MyState.Failure -> message
 *     else -> null
 *   }
 * ```
 *
 * # Which parents get an accessor
 *
 * Accessors are generated for **every transitive sealed supertype** of the enclosing class,
 * so an intermediate sealed type gets its own accessor too. A sealed parent annotated with
 * [ChildOptionals] is generated by that annotation instead (which still honours this
 * annotation's [propertyName] / [kdoc] / [visibility]); see [ChildOptionals].
 *
 * # Difference from [ChildOptionals]
 *
 * `@ParentOptional` opts in **one property at a time** (annotate each property you want).
 * [ChildOptionals] is placed on the sealed **parent** and applies to every eligible property
 * of every concrete leaf at once. Use `@ParentOptional` for a hand-picked surface, and
 * [ChildOptionals] for blanket application.
 *
 * # Notes on property shapes
 *
 * - **Nullable property types** (`String?`) are allowed and keep their type as-is (the `?` is
 *   never doubled) — but the accessor's `null` is then ambiguous: it can mean "the receiver is
 *   not such a child" or the property's own `null` value. The generated KDoc carries this note;
 *   use an `is` check when the distinction matters.
 * - **`@Deprecated`** on the annotated property (or its child class) is propagated onto the
 *   generated accessor, so reading a deprecated property through the accessor keeps warning at
 *   call sites (and the generated code itself stays warning-free).
 * - **Extension properties** cannot be annotated (compilation error): the accessor cannot supply
 *   the extension receiver.
 * - **Type parameters**: the property type may only reference type parameters the sealed parent
 *   pins *directly* (`Child<T> : Parent<T>`); anything else is a compilation error.
 * - **Typealiased types** are preserved as the alias in the generated signature; merging an
 *   aliased and a non-aliased spelling of the same type is a type-mismatch error.
 * - **`lateinit var`** is allowed; like a direct read, the accessor throws if it is read before
 *   initialization.
 *
 * @property propertyName Name of the generated extension property. Defaults to `""`, which
 *   means "same name as the annotated property". Set e.g. `propertyName = "dataOrNull"` when
 *   the original name would clash or when an `...OrNull` style reads better at call sites.
 * @property kdoc Custom KDoc (description / examples) injected into the generated accessor's
 *   KDoc, the same way as cream's other source annotations. See [KDoc].
 * @property visibility Visibility modifier of the generated extension property. Defaults to
 *   [CopyVisibility.INHERIT]: the `cream.defaultVisibility` option applies first, then the
 *   accessor inherits the narrowest visibility among the sealed parent, the child, and the
 *   property. Forcing [CopyVisibility.PUBLIC] is a compilation error when the accessor's
 *   signature would expose an internal symbol (the sealed parent or the property type).
 *
 * @see ChildOptionals
 * @see CopyVisibility
 * @see KDoc
 */
@Target(AnnotationTarget.PROPERTY)
@Retention(AnnotationRetention.SOURCE)
public annotation class ParentOptional(
    val propertyName: String = "",
    val kdoc: KDoc = KDoc(),
    val visibility: CopyVisibility = CopyVisibility.INHERIT,
)
