package me.tbsten.cream.ksp.core.copyFun

import com.google.devtools.ksp.getConstructors
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.google.devtools.ksp.symbol.KSTypeParameter
import me.tbsten.cream.ksp.core.common.GenerateSourceAnnotation
import me.tbsten.cream.ksp.core.common.ValueClassConversionOutcome
import me.tbsten.cream.ksp.core.common.appendAutoGeneratedFunctionKDoc
import me.tbsten.cream.ksp.core.common.appendConstructorCallBody
import me.tbsten.cream.ksp.core.common.appendExample
import me.tbsten.cream.ksp.core.common.appendSourceClassWithTypeArgs
import me.tbsten.cream.ksp.core.common.appendTargetClassWithTypeArgs
import me.tbsten.cream.ksp.core.common.appendTypeParameterList
import me.tbsten.cream.ksp.core.common.appendWhereClause
import me.tbsten.cream.ksp.core.common.defaultValueExpression
import me.tbsten.cream.ksp.core.common.deprecatedAnnotationLine
import me.tbsten.cream.ksp.core.common.findMatchedProperty
import me.tbsten.cream.ksp.core.common.findValueClassConversion
import me.tbsten.cream.ksp.core.common.findValueClassConversionOutcome
import me.tbsten.cream.ksp.core.common.getCopyFunctionTypeParameters
import me.tbsten.cream.ksp.core.common.isExcludedFromCopy
import me.tbsten.cream.ksp.core.common.resolveConstructorParamTypeParameter
import me.tbsten.cream.ksp.core.common.resolveFunName
import me.tbsten.cream.ksp.core.common.toModifierString
import me.tbsten.cream.ksp.core.common.underPackageName
import me.tbsten.cream.ksp.core.common.warnIfTargetExcludeHasNoEffect
import me.tbsten.cream.ksp.options.CreamOptions
import me.tbsten.cream.ksp.util.escapeKotlinIdentifier
import me.tbsten.cream.ksp.util.ksp.asString

context(options: CreamOptions, logger: KSPLogger)
internal fun Appendable.appendCopyToClassFunction(
    source: KSClassDeclaration,
    targetClass: KSClassDeclaration,
    generateSourceAnnotation: GenerateSourceAnnotation,
    omitPackages: List<String>,
) {
    targetClass.getConstructors().forEach { constructor ->
        val typeParameters =
            getCopyFunctionTypeParameters(
                sourceClass = source,
                targetConstructor = constructor,
            )

        // Generate copy function
        val funName =
            resolveFunName(
                funNameTemplate = generateSourceAnnotation.funNameTemplate,
                source = source,
                target = targetClass,
                options = options,
            )

        // A parameter is REQUIRED when it does NOT receive a default (`= this.x`, or a
        // value-class wrap/unwrap) in the emitted signature, mirroring the default-emission
        // conditions below. `.Exclude` wins over BOTH default kinds: an excluded matched
        // property and an excluded conversion-resolved property each leave the parameter
        // required.
        val requiredParamNames =
            constructor.parameters
                .filter { parameter ->
                    val matched = parameter.findMatchedProperty(source, generateSourceAnnotation)
                    if (matched != null) {
                        parameter.isExcludedFromCopy(matched, source, generateSourceAnnotation)
                    } else {
                        val conversion = parameter.findValueClassConversion(source, generateSourceAnnotation)
                        conversion == null ||
                            parameter.isExcludedFromCopy(conversion.sourceProperty, source, generateSourceAnnotation)
                    }
                }.map { it.name!!.asString() }

        appendCopyToClassKDoc(source, targetClass, generateSourceAnnotation, funName, requiredParamNames)

        deprecatedAnnotationLine(listOf(source))?.let { appendLine(it) }

        append("${generateSourceAnnotation.visibility.toModifierString(targetClass)} fun ")
        appendTypeParameterList(typeParameters, omitPackages)
        append(" ")
        appendSourceClassWithTypeArgs(source, targetClass, typeParameters)
        append(".")
        append("$funName(")
        appendLine()

        // The same renderer produces the parameter type AND any value-class constructor call in
        // its default, so the two can never disagree on omitted packages / type parameters.
        val renderType: (KSType) -> String = { type ->
            type.asString(
                omitPackages = omitPackages,
                typeParameterToString = {
                    resolveConstructorParamTypeParameter(
                        it.declaration as KSTypeParameter,
                        source,
                        targetClass,
                        typeParameters,
                    )
                },
            )
        }

        constructor.parameters.forEach { parameter ->
            val paramName = parameter.name!!.asString()
            val paramType = renderType(parameter.type.resolve())
            val modifiers = if (parameter.isVararg) "vararg " else ""
            append("    $modifiers${paramName.escapeKotlinIdentifier()}: $paramType")

            val matchedProperty = parameter.findMatchedProperty(source, generateSourceAnnotation)
            // No type-compatible match: a value-class wrap/unwrap may still supply a default
            // (issue #21). Kept parallel to the matched-property branch below.
            val conversionOutcome =
                if (matchedProperty == null) {
                    parameter.findValueClassConversionOutcome(source, generateSourceAnnotation)
                } else {
                    ValueClassConversionOutcome.None
                }
            parameter.warnIfTargetExcludeHasNoEffect(
                hasCandidateDefault = matchedProperty != null || conversionOutcome is ValueClassConversionOutcome.Applied,
                generateSourceAnnotation = generateSourceAnnotation,
                logger = logger,
            )
            if (matchedProperty != null) {
                if (!parameter.isExcludedFromCopy(matchedProperty, source, generateSourceAnnotation)) {
                    append(" = this.${matchedProperty.simpleName.asString().escapeKotlinIdentifier()}")
                }
            } else {
                when (conversionOutcome) {
                    is ValueClassConversionOutcome.Applied -> {
                        val conversion = conversionOutcome.conversion
                        // `.Exclude` wins over the conversion: the parameter stays required.
                        if (!parameter.isExcludedFromCopy(conversion.sourceProperty, source, generateSourceAnnotation)) {
                            val sourceAccess =
                                "this.${conversion.sourceProperty.simpleName.asString().escapeKotlinIdentifier()}"
                            append(" = ${conversion.defaultValueExpression(sourceAccess, renderType)}")
                        }
                    }

                    // An almost-conversion (nullability / visibility) is plausibly a user error;
                    // warn unless the candidate is `@Exclude`-marked (an explicit opt-out).
                    is ValueClassConversionOutcome.NearMiss ->
                        if (!parameter.isExcludedFromCopy(conversionOutcome.candidate, source, generateSourceAnnotation)) {
                            logger.warn(conversionOutcome.message, parameter)
                        }

                    is ValueClassConversionOutcome.None -> Unit
                }
            }
            append(",\n")
        }
        append(") : ")
        appendTargetClassWithTypeArgs(source, targetClass, typeParameters)
        appendWhereClause(typeParameters, omitPackages)
        appendConstructorCallBody(targetClass, constructor)
    }
}

private fun Appendable.appendCopyToClassKDoc(
    source: KSClassDeclaration,
    target: KSClassDeclaration,
    generateSourceAnnotation: GenerateSourceAnnotation,
    funName: String,
    requiredParamNames: List<String>,
) {
    val requiredArgs = requiredParamNames.joinToString(", ") { "$it = $it" }
    val basicCall = if (requiredArgs.isEmpty()) "" else requiredArgs
    val overrideCall =
        if (requiredArgs.isEmpty()) "property = value" else "$requiredArgs, property = value"
    appendAutoGeneratedFunctionKDoc(
        generateSourceAnnotation = generateSourceAnnotation,
        seeClasses = listOf(source, target),
        autoDescription = {
            appendLine("${source.underPackageName} -> ${target.underPackageName} copy function.")
        },
        autoExamples = {
            appendExample(
                "Example: Basic",
                """
                val source = ${source.simpleName.asString()}(...)
                val target = source.$funName($basicCall)
                """.trimIndent(),
            )

            appendExample(
                "Example: Override property values",
                """
                val source = ${source.simpleName.asString()}(...)
                val target = source.$funName($overrideCall)
                """.trimIndent(),
            )
        },
    )
}
