package me.tbsten.cream.ksp.core.copyFun

import com.google.devtools.ksp.getConstructors
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSDeclaration
import com.google.devtools.ksp.symbol.KSTypeParameter
import me.tbsten.cream.ksp.core.common.GenerateSourceAnnotation
import me.tbsten.cream.ksp.core.common.appendAutoGeneratedFunctionKDoc
import me.tbsten.cream.ksp.core.common.appendConstructorCallBody
import me.tbsten.cream.ksp.core.common.appendExample
import me.tbsten.cream.ksp.core.common.appendSourceClassWithTypeArgs
import me.tbsten.cream.ksp.core.common.appendTargetClassWithTypeArgs
import me.tbsten.cream.ksp.core.common.appendTypeParameterList
import me.tbsten.cream.ksp.core.common.appendWhereClause
import me.tbsten.cream.ksp.core.common.deprecatedAnnotationLine
import me.tbsten.cream.ksp.core.common.findMatchedProperty
import me.tbsten.cream.ksp.core.common.getCopyFunctionTypeParameters
import me.tbsten.cream.ksp.core.common.isExcludedFromCopy
import me.tbsten.cream.ksp.core.common.resolveConstructorParamTypeParameter
import me.tbsten.cream.ksp.core.common.resolveFunName
import me.tbsten.cream.ksp.core.common.toModifierString
import me.tbsten.cream.ksp.core.common.underPackageName
import me.tbsten.cream.ksp.core.common.warnIfTargetExcludeHasNoEffect
import me.tbsten.cream.ksp.options.CreamOptions
import me.tbsten.cream.ksp.util.escapeKotlinIdentifier
import me.tbsten.cream.ksp.util.ksp.asString
import java.io.BufferedWriter

context(options: CreamOptions, logger: KSPLogger)
internal fun BufferedWriter.appendCopyToClassFunction(
    source: KSClassDeclaration,
    targetClass: KSClassDeclaration,
    generateSourceAnnotation: GenerateSourceAnnotation,
    omitPackages: List<String>,
    annotated: KSDeclaration = source,
) {
    targetClass.getConstructors().forEach { constructor ->
        val typeParameters =
            getCopyFunctionTypeParameters(
                sourceClass = source,
                targetConstructor = constructor,
            )

        // Generate copy function
        val funName =
            resolveFunName(
                funNameTemplate = generateSourceAnnotation.funNameTemplate,
                source = source,
                target = targetClass,
                options = options,
            )

        // A parameter is REQUIRED when it does NOT receive a `= this.x` default in the emitted
        // signature, mirroring the default-emission condition below.
        val requiredParamNames =
            constructor.parameters
                .filter { parameter ->
                    val matched = parameter.findMatchedProperty(source, generateSourceAnnotation)
                    matched == null || parameter.isExcludedFromCopy(matched, source, generateSourceAnnotation)
                }.map { it.name!!.asString() }

        appendCopyToClassKDoc(source, targetClass, generateSourceAnnotation, annotated, funName, requiredParamNames)

        deprecatedAnnotationLine(listOf(source))?.let { appendLine(it) }

        append("${generateSourceAnnotation.visibility.toModifierString(targetClass)} fun ")
        appendTypeParameterList(typeParameters, omitPackages)
        append(" ")
        appendSourceClassWithTypeArgs(source, targetClass, typeParameters)
        append(".")
        append("$funName(")
        appendLine()

        constructor.parameters.forEach { parameter ->
            val paramName = parameter.name!!.asString()
            val paramType =
                parameter.type
                    .resolve()
                    .asString(
                        omitPackages = omitPackages,
                        typeParameterToString = {
                            resolveConstructorParamTypeParameter(
                                it.declaration as KSTypeParameter,
                                source,
                                targetClass,
                                typeParameters,
                            )
                        },
                    )
            val modifiers = if (parameter.isVararg) "vararg " else ""
            append("    $modifiers${paramName.escapeKotlinIdentifier()}: $paramType")

            val matchedProperty = parameter.findMatchedProperty(source, generateSourceAnnotation)
            parameter.warnIfTargetExcludeHasNoEffect(matchedProperty, generateSourceAnnotation, logger)
            if (matchedProperty != null &&
                !parameter.isExcludedFromCopy(matchedProperty, source, generateSourceAnnotation)
            ) {
                append(" = this.${matchedProperty.simpleName.asString().escapeKotlinIdentifier()}")
            }
            append(",\n")
        }
        append(") : ")
        appendTargetClassWithTypeArgs(source, targetClass, typeParameters)
        appendWhereClause(typeParameters, omitPackages)
        appendConstructorCallBody(targetClass, constructor)
    }
}

private fun BufferedWriter.appendCopyToClassKDoc(
    source: KSClassDeclaration,
    target: KSClassDeclaration,
    generateSourceAnnotation: GenerateSourceAnnotation,
    annotated: KSDeclaration,
    funName: String,
    requiredParamNames: List<String>,
) {
    val requiredArgs = requiredParamNames.joinToString(", ") { "$it = $it" }
    val basicCall = if (requiredArgs.isEmpty()) "" else requiredArgs
    val overrideCall =
        if (requiredArgs.isEmpty()) "property = value" else "$requiredArgs, property = value"
    appendAutoGeneratedFunctionKDoc(
        generateSourceAnnotation = generateSourceAnnotation,
        annotated = annotated,
        seeClasses = listOf(source, target),
        autoDescription = {
            appendLine("${source.underPackageName} -> ${target.underPackageName} copy function.")
        },
        autoExamples = {
            appendExample(
                "Example: Basic",
                """
                val source = ${source.simpleName.asString()}(...)
                val target = source.$funName($basicCall)
                """.trimIndent(),
            )

            appendExample(
                "Example: Override property values",
                """
                val source = ${source.simpleName.asString()}(...)
                val target = source.$funName($overrideCall)
                """.trimIndent(),
            )
        },
    )
}
