package me.tbsten.cream.ksp.core.copyFun

import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSDeclaration
import me.tbsten.cream.ksp.GenerateSourceAnnotation
import me.tbsten.cream.ksp.core.common.appendAutoGeneratedFunctionKDoc
import me.tbsten.cream.ksp.core.common.appendExample
import me.tbsten.cream.ksp.core.common.fullName
import me.tbsten.cream.ksp.core.common.resolveFunName
import me.tbsten.cream.ksp.core.common.toModifierString
import me.tbsten.cream.ksp.core.common.underPackageName
import me.tbsten.cream.ksp.options.CreamOptions
import java.io.BufferedWriter

context(options: CreamOptions)
internal fun BufferedWriter.appendCopyToObjectFunction(
    source: KSClassDeclaration,
    targetObject: KSClassDeclaration,
    generateSourceAnnotation: GenerateSourceAnnotation<*>,
    annotated: KSDeclaration = source,
) {
    val funName =
        resolveFunName(
            funNameTemplate = generateSourceAnnotation.funNameTemplate,
            source = source,
            target = targetObject,
            options = options,
        )
    appendCopyToObjectKDoc(source, targetObject, generateSourceAnnotation, annotated, funName)
    append("${generateSourceAnnotation.visibility.toModifierString(targetObject)} fun ")
    append(source.fullName)

    if (source.typeParameters.isNotEmpty()) {
        append("<")
        append(
            source.typeParameters
                .joinToString(", ") { "*" },
        )
        append(">")
    }

    append(".$funName() = ${targetObject.fullName}")
    appendLine()
}

private fun BufferedWriter.appendCopyToObjectKDoc(
    source: KSClassDeclaration,
    target: KSClassDeclaration,
    generateSourceAnnotation: GenerateSourceAnnotation<*>,
    annotated: KSDeclaration,
    funName: String,
) {
    appendAutoGeneratedFunctionKDoc(
        generateSourceAnnotation = generateSourceAnnotation,
        annotated = annotated,
        seeClasses = listOf(source, target),
        autoDescription = {
            appendLine("${source.underPackageName} -> ${target.underPackageName} copy function.")
        },
        autoExamples = {
            appendExample(
                "Example: Basic",
                """
                val source = ${source.simpleName.asString()}(...)
                val target = source.$funName()
                """.trimIndent(),
            )
        },
    )
}
