package me.tbsten.cream.ksp.transform

import com.google.devtools.ksp.symbol.KSClassDeclaration
import me.tbsten.cream.ksp.GenerateSourceAnnotation
import me.tbsten.cream.ksp.util.underPackageName
import java.io.BufferedWriter

internal fun BufferedWriter.appendAutoGeneratedFunctionKDoc(
    generateSourceAnnotation: GenerateSourceAnnotation<*>,
    seeClasses: List<KSClassDeclaration>,
    content: KDocWriter.() -> Unit,
) {
    appendLine("/**")
    appendLine(" * (${autoGenerateKDoc(generateSourceAnnotation)})")
    appendLine(" * ")
    content(KDocWriter(" * ", this))
    appendLine(" * ")
    seeClasses.forEach {
        appendLine(" * @see ${it.underPackageName}")
    }
    appendLine(" */")
}

internal class KDocWriter(
    private val prefix: String,
    private val writer: BufferedWriter,
) {
    fun appendLine(value: String = "") {
        writer.appendLine("${prefix}${value}")
    }
}

private fun autoGenerateKDoc(generateSourceAnnotation: GenerateSourceAnnotation<*>): String =
    buildString {
        append("Auto generate by @[")
        append(generateSourceAnnotation.annotationClass.simpleName)
        append("] annotation of [")
        append(generateSourceAnnotation.annotationTarget.underPackageName)
        append("]")
    }
