package me.tbsten.cream.ksp.transform

import com.google.devtools.ksp.symbol.KSClassDeclaration
import me.tbsten.cream.CopyVisibility
import me.tbsten.cream.DefaultCopyFunctionName
import me.tbsten.cream.ksp.GenerateSourceAnnotation
import me.tbsten.cream.ksp.options.CreamOptions
import me.tbsten.cream.ksp.util.fullName
import me.tbsten.cream.ksp.util.toModifierString
import me.tbsten.cream.ksp.util.underPackageName
import java.io.BufferedWriter

internal fun BufferedWriter.appendCopyToObjectFunction(
    source: KSClassDeclaration,
    targetObject: KSClassDeclaration,
    generateSourceAnnotation: GenerateSourceAnnotation<*>,
    options: CreamOptions,
    visibility: CopyVisibility = CopyVisibility.INHERIT,
    funNameTemplate: String = DefaultCopyFunctionName,
) {
    val funName =
        resolveFunName(
            funNameTemplate = funNameTemplate,
            source = source,
            target = targetObject,
            options = options,
        )
    appendCopyToObjectKDoc(source, targetObject, generateSourceAnnotation, funName)
    append("${visibility.toModifierString(targetObject)} fun ")
    append(source.fullName)

    if (source.typeParameters.isNotEmpty()) {
        append("<")
        append(
            source.typeParameters
                .joinToString(", ") { "*" },
        )
        append(">")
    }

    append(".$funName() = ${targetObject.fullName}")
    appendLine()
}

internal fun BufferedWriter.appendCombineToObjectFunction(
    primarySource: KSClassDeclaration,
    otherSources: List<KSClassDeclaration>,
    targetObject: KSClassDeclaration,
    generateSourceAnnotation: GenerateSourceAnnotation<*>,
    options: CreamOptions,
    visibility: CopyVisibility = CopyVisibility.INHERIT,
    funNameTemplate: String = DefaultCopyFunctionName,
) {
    val allSources = listOf(primarySource) + otherSources
    val funName =
        resolveFunName(
            funNameTemplate = funNameTemplate,
            source = primarySource,
            target = targetObject,
            options = options,
        )
    appendCombineToObjectKDoc(allSources, targetObject, generateSourceAnnotation, funName)
    appendLine(
        "${visibility.toModifierString(targetObject)} fun ${primarySource.fullName}.$funName(${
            otherSources.joinToString(", ") { otherSource ->
                "${otherSource.underPackageName.replaceFirstChar { it.lowercase() }}: ${otherSource.fullName}"
            }
        }) = ${targetObject.fullName}",
    )
}

private fun BufferedWriter.appendCombineToObjectKDoc(
    sources: List<KSClassDeclaration>,
    target: KSClassDeclaration,
    generateSourceAnnotation: GenerateSourceAnnotation<*>,
    funName: String,
) {
    appendAutoGeneratedFunctionKDoc(
        generateSourceAnnotation = generateSourceAnnotation,
        seeClasses = sources + target,
        autoDescription = {
            appendCombineAutoDescription(sources, target)
        },
        autoExamples = {
            appendExample("Example: Basic", combineExampleBody(sources, funName))
        },
    )
}

private fun BufferedWriter.appendCopyToObjectKDoc(
    source: KSClassDeclaration,
    target: KSClassDeclaration,
    generateSourceAnnotation: GenerateSourceAnnotation<*>,
    funName: String,
) {
    appendAutoGeneratedFunctionKDoc(
        generateSourceAnnotation = generateSourceAnnotation,
        seeClasses = listOf(source, target),
        autoDescription = {
            appendLine("${source.underPackageName} -> ${target.underPackageName} copy function.")
        },
        autoExamples = {
            appendExample(
                "Example: Basic",
                """
                val source = ${source.simpleName.asString()}(...)
                val target = source.$funName()
                """.trimIndent(),
            )
        },
    )
}
