package me.tbsten.cream.ksp.core.common

import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSPropertyDeclaration
import com.google.devtools.ksp.symbol.KSValueParameter

/**
 * Resolves the SOURCE property that supplies a TARGET constructor parameter's auto-copy default
 * through an explicit remapping — cream's `.Map` annotations, or whatever a non-annotation caller
 * decides — returning `null` when no remapping names that parameter.
 *
 * Returning `null` is the normal case: [findMatchedProperty] then falls back to the shared plain
 * name match, which every generation gets for free. Only the explicit remapping travels through
 * here, which is what keeps one annotation's `.Map` from affecting functions generated by another.
 *
 * A standalone type rather than a [GenerateSourceAnnotation] member so the `core` generators take
 * it as an ordinary parameter: a caller driving generation from something other than an annotation
 * supplies a lambda instead of implementing an interface.
 *
 * Parameters, in order:
 *  - `parameter` — the target constructor parameter being resolved,
 *  - `source` — the source class to look the property up in,
 *  - `parameterName` — `parameter`'s name, already resolved by the caller (a parameter without one
 *    never reaches here),
 *  - `accepts` — the acceptance test a candidate property must pass before the remapping commits
 *    to it. [findMatchedProperty] instantiates it with type compatibility (the normal auto-copy
 *    default resolution); the automatic value-class conversion
 *    ([findValueClassConversionOutcome]) instantiates it with value-class convertibility, which
 *    is what makes `.Map`-renamed properties wrap/unwrap exactly like plain name matches
 *    (issue #21). A rejected candidate falls through to the plain name match.
 */
internal typealias FindMappedSourceProperty = (
    parameter: KSValueParameter,
    source: KSClassDeclaration,
    parameterName: String,
    accepts: (KSPropertyDeclaration) -> Boolean,
) -> KSPropertyDeclaration?
