package me.tbsten.cream.ksp.core.common

import com.google.devtools.ksp.getAnnotationsByType
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSPropertyDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.google.devtools.ksp.symbol.KSTypeParameter
import com.google.devtools.ksp.symbol.KSValueParameter
import me.tbsten.cream.CombineFrom
import me.tbsten.cream.CombineTo
import me.tbsten.cream.CopyFrom
import me.tbsten.cream.CopyTo
import me.tbsten.cream.CopyToChildren

/**
 * Resolve which SOURCE property supplies the default value for this TARGET constructor parameter.
 *
 * The `.Map` lookup is scoped to the [generateSourceAnnotation] that triggered this generation —
 * a `.Map` belonging to one annotation never affects functions generated by another (e.g. a
 * `@CopyTo.Map` on a source parameter does not remap a `@CopyFrom`-generated function from the
 * same class), mirroring the annotation-scoped `@Exclude` handling in [isExcludedFromCopy].
 * When the scoped lookup finds nothing, a plain name match is the shared fallback.
 *
 * Where each annotation's `.Map` is read from:
 *
 * - `@CopyTo.Map` / `@CombineTo.Map`: on the SOURCE side (a property or its constructor
 *   parameter); its values name TARGET parameters.
 * - `@CopyFrom.Map`: on the TARGET constructor parameter; its values name SOURCE properties.
 * - `@CombineFrom.Map`: both placements — on the target parameter naming source properties,
 *   or on the source side naming target parameters.
 * - `@CopyToChildren.Map`: on a sealed parent's property only.
 * - `@CopyMapping` / `@CombineMapping`: not read from properties at all — their
 *   `properties = [Map(source, target)]` annotation arguments arrive via
 *   [GenerateSourceAnnotation].
 * - `@SealedCopy`: never resolves defaults through this function; its `Map` has Via-parameter
 *   semantics handled in `core/sealedCopy`.
 *
 * Source-side lookups are two-step (property first, then its constructor parameter); see
 * [findSourcePropertyWithMapAnnotationOnSource] for why.
 */
internal fun KSValueParameter.findMatchedProperty(
    source: KSClassDeclaration,
    generateSourceAnnotation: GenerateSourceAnnotation,
): KSPropertyDeclaration? =
    findPropertyByNameResolution(source, generateSourceAnnotation) {
        matchesSourcePropertyType(it.type.resolve())
    }

/**
 * Resolves this target constructor parameter to a source property by NAME, walking the same
 * annotation-scoped resolution ladder for every caller: the [generateSourceAnnotation]'s own
 * explicit `.Map` annotations (on either side) or its mapping `properties` remappings, then the
 * plain name match. Each step only commits to a property that [accepts]; a rejected candidate
 * falls through to the next step, so the ladder's fall-through semantics are identical no matter
 * the acceptance test.
 *
 * [findMatchedProperty] instantiates it with type compatibility ([matchesSourcePropertyType]) —
 * the normal auto-copy default resolution. The automatic value-class conversion
 * ([findValueClassConversionOutcome]) instantiates it with value-class convertibility, which is
 * what makes `.Map`-renamed properties wrap/unwrap exactly like plain name matches.
 */
internal fun KSValueParameter.findPropertyByNameResolution(
    source: KSClassDeclaration,
    generateSourceAnnotation: GenerateSourceAnnotation,
    accepts: (KSPropertyDeclaration) -> Boolean,
): KSPropertyDeclaration? {
    val parameterName =
        this.name?.asString()
            ?: return null

    val mappedProperty =
        when (generateSourceAnnotation) {
            is GenerateSourceAnnotation.CopyTo ->
                findSourcePropertyWithCopyToMapAnnotation(source, parameterName, accepts)
            is GenerateSourceAnnotation.CombineTo ->
                findSourcePropertyWithCombineToMapAnnotation(source, parameterName, accepts)
            is GenerateSourceAnnotation.CopyToChildren ->
                findSourcePropertyWithCopyToChildrenMapAnnotation(source, parameterName, accepts)
            is GenerateSourceAnnotation.CopyFrom ->
                findSourcePropertyWithCopyFromMapAnnotation(source, accepts)
            is GenerateSourceAnnotation.CombineFrom ->
                findSourcePropertyWithCombineFromMapAnnotationOnTarget(source, accepts)
                    ?: findSourcePropertyWithCombineFromMapAnnotationOnSource(source, parameterName, accepts)
            is GenerateSourceAnnotation.CopyMapping ->
                findSourcePropertyWithPropertyMappings(source, parameterName, generateSourceAnnotation.propertyMappings, accepts)
            is GenerateSourceAnnotation.CombineMapping ->
                findSourcePropertyWithPropertyMappings(source, parameterName, generateSourceAnnotation.propertyMappings, accepts)
            is GenerateSourceAnnotation.SealedCopy -> null
        }

    return mappedProperty ?: findSourcePropertyByName(source, parameterName, accepts)
}

/**
 * Find source property using explicit property mappings (used by both CopyMapping and CombineMapping).
 *
 * Property mappings define explicit source -> target property name mappings.
 * For example, if mapping is ("xProp" -> "yProp"), then when looking for target parameter "yProp",
 * this function will find source property "xProp".
 */
private fun KSValueParameter.findSourcePropertyWithPropertyMappings(
    source: KSClassDeclaration,
    parameterName: String,
    propertyMappings: List<Pair<String, String>>,
    accepts: (KSPropertyDeclaration) -> Boolean,
): KSPropertyDeclaration? {
    val sourcePropertyName =
        propertyMappings
            .firstOrNull { (_, target) ->
                target == parameterName
            }?.first ?: return null

    return source
        .getAllProperties()
        .firstOrNull {
            it.simpleName.asString() == sourcePropertyName && accepts(it)
        }
}

/**
 * Shared SOURCE-side lookup for `.Map` annotations placed on the source class
 * (`@CopyTo.Map` / `@CombineTo.Map` / `@CombineFrom.Map` on the source side).
 *
 * The annotation [T] is searched at two sites, property site first:
 * 1. on the source property itself, then
 * 2. on the primary-constructor parameter of the same name.
 *
 * Step 2 exists because `data class Source(@CopyTo.Map("x") val y: ...)` without a use-site
 * target attaches the annotation to the constructor PARAMETER, not the property, so a
 * property-site-only lookup would miss it.
 *
 * A source property matches when [parameterName] is listed in the annotation's `propertyNames`
 * (extracted via [propertyNamesOf]) and the candidate [accepts] this target parameter.
 */
private inline fun <reified T : Annotation> KSValueParameter.findSourcePropertyWithMapAnnotationOnSource(
    source: KSClassDeclaration,
    parameterName: String,
    accepts: (KSPropertyDeclaration) -> Boolean,
    propertyNamesOf: (T) -> Array<out String>,
): KSPropertyDeclaration? =
    source
        .getAllProperties()
        .firstOrNull { sourceProperty ->
            val mapAnnotation =
                sourceProperty
                    .getAnnotationsByType(T::class)
                    .firstOrNull()
                    ?: source.primaryConstructor
                        ?.parameters
                        ?.firstOrNull { it.name?.asString() == sourceProperty.simpleName.asString() }
                        ?.getAnnotationsByType(T::class)
                        ?.firstOrNull()

            mapAnnotation != null &&
                parameterName in propertyNamesOf(mapAnnotation) &&
                accepts(sourceProperty)
        }

private fun KSValueParameter.findSourcePropertyWithCopyToMapAnnotation(
    source: KSClassDeclaration,
    parameterName: String,
    accepts: (KSPropertyDeclaration) -> Boolean,
): KSPropertyDeclaration? = findSourcePropertyWithMapAnnotationOnSource<CopyTo.Map>(source, parameterName, accepts) { it.propertyNames }

private fun KSValueParameter.findSourcePropertyWithCombineToMapAnnotation(
    source: KSClassDeclaration,
    parameterName: String,
    accepts: (KSPropertyDeclaration) -> Boolean,
): KSPropertyDeclaration? = findSourcePropertyWithMapAnnotationOnSource<CombineTo.Map>(source, parameterName, accepts) { it.propertyNames }

/**
 * Find source property using @CopyToChildren.Map annotation on a sealed parent's property.
 *
 * Scoped to @CopyToChildren generation (the caller checks [GenerateSourceAnnotation.CopyToChildren])
 * so the mapping does not leak into functions generated by other cream annotations on the same
 * sealed type — mirroring the annotation-scoped handling of @CopyToChildren.Exclude.
 * @CopyToChildren.Map targets PROPERTY only, so unlike
 * [findSourcePropertyWithMapAnnotationOnSource] no constructor-parameter fallback lookup is
 * needed (a sealed parent's abstract property has no constructor parameter anyway).
 */
private fun KSValueParameter.findSourcePropertyWithCopyToChildrenMapAnnotation(
    source: KSClassDeclaration,
    parameterName: String,
    accepts: (KSPropertyDeclaration) -> Boolean,
): KSPropertyDeclaration? =
    source
        .getAllProperties()
        .firstOrNull { sourceProperty ->
            val mapAnnotation =
                sourceProperty
                    .getAnnotationsByType(CopyToChildren.Map::class)
                    .firstOrNull()

            if (mapAnnotation != null) {
                parameterName in mapAnnotation.propertyNames &&
                    accepts(sourceProperty)
            } else {
                false
            }
        }

/**
 * Find source property using @CombineFrom.Map annotation on target parameter.
 * Target parameter specifies which source property to use.
 * Example: @CombineFrom.Map("sourcePropertyB") val targetProperty: String
 */
private fun KSValueParameter.findSourcePropertyWithCombineFromMapAnnotationOnTarget(
    source: KSClassDeclaration,
    accepts: (KSPropertyDeclaration) -> Boolean,
): KSPropertyDeclaration? {
    val combineFromPropertyAnnotation =
        this
            .getAnnotationsByType(CombineFrom.Map::class)
            .firstOrNull()

    if (combineFromPropertyAnnotation != null) {
        val sourcePropertyNames = combineFromPropertyAnnotation.propertyNames

        return source
            .getAllProperties()
            .firstOrNull {
                it.simpleName.asString() in sourcePropertyNames && accepts(it)
            }
    }

    return null
}

/**
 * Find source property using @CombineFrom.Map annotation on source property.
 * Source property specifies which target parameters it maps to.
 * Example: @CombineFrom.Map("targetPropertyA") val sourceProperty: String
 */
private fun KSValueParameter.findSourcePropertyWithCombineFromMapAnnotationOnSource(
    source: KSClassDeclaration,
    parameterName: String,
    accepts: (KSPropertyDeclaration) -> Boolean,
): KSPropertyDeclaration? = findSourcePropertyWithMapAnnotationOnSource<CombineFrom.Map>(source, parameterName, accepts) { it.propertyNames }

private fun KSValueParameter.findSourcePropertyWithCopyFromMapAnnotation(
    source: KSClassDeclaration,
    accepts: (KSPropertyDeclaration) -> Boolean,
): KSPropertyDeclaration? {
    val copyFromPropertyAnnotation =
        this
            .getAnnotationsByType(CopyFrom.Map::class)
            .firstOrNull()

    if (copyFromPropertyAnnotation != null) {
        val sourcePropertyNames = copyFromPropertyAnnotation.propertyNames

        return source
            .getAllProperties()
            .firstOrNull {
                it.simpleName.asString() in sourcePropertyNames && accepts(it)
            }
    }

    return null
}

private fun KSValueParameter.findSourcePropertyByName(
    source: KSClassDeclaration,
    parameterName: String,
    accepts: (KSPropertyDeclaration) -> Boolean,
): KSPropertyDeclaration? =
    source
        .getAllProperties()
        .firstOrNull {
            it.simpleName.asString() == parameterName && accepts(it)
        }

/**
 * Element qualified name -> the primitive array qualified name a non-null primitive `vararg`
 * exposes. A `vararg nums: Int` property is an `IntArray` (not `Array<Int>`), so a source
 * property matching it must be that exact primitive array. Nullable primitives box to
 * `Array<out E?>` and are handled via the [kotlin.Array] branch instead.
 */
private val primitiveArrayByElement =
    mapOf(
        "kotlin.Int" to "kotlin.IntArray",
        "kotlin.Long" to "kotlin.LongArray",
        "kotlin.Short" to "kotlin.ShortArray",
        "kotlin.Byte" to "kotlin.ByteArray",
        "kotlin.Char" to "kotlin.CharArray",
        "kotlin.Boolean" to "kotlin.BooleanArray",
        "kotlin.Float" to "kotlin.FloatArray",
        "kotlin.Double" to "kotlin.DoubleArray",
        "kotlin.UInt" to "kotlin.UIntArray",
        "kotlin.ULong" to "kotlin.ULongArray",
        "kotlin.UShort" to "kotlin.UShortArray",
        "kotlin.UByte" to "kotlin.UByteArray",
    )

/**
 * Compatibility check between this target constructor parameter and a candidate source
 * property's type, accounting for `vararg`.
 *
 * For a non-`vararg` parameter this is the plain [isTypeCompatible] element comparison.
 * For a `vararg` parameter, `this.type.resolve()` is the ELEMENT type but the property the
 * source exposes is an ARRAY, so the element type must be lifted to the corresponding array
 * type before comparing:
 * - non-null primitive element -> source must be the matching primitive array (e.g. `IntArray`)
 * - object element (or nullable primitive, which boxes to `Array<out E?>`) -> source must be
 *   `kotlin.Array<out E'>` whose element `E'` is compatible with `E`.
 */
private fun KSValueParameter.matchesSourcePropertyType(sourceType: KSType): Boolean {
    val targetElementType = this.type.resolve()
    if (!this.isVararg) return isTypeCompatible(targetElementType, sourceType)

    // A vararg parameter is backed by a NON-NULL array (`Array<out E>` / `IntArray`), so a
    // nullable source array cannot supply its `= this.x` default without a type error. Reject it
    // here; the parameter then becomes a required vararg, which compiles.
    if (sourceType.isMarkedNullable) return false

    val sourceName = sourceType.declaration.qualifiedName?.asString()
    val targetElementName = targetElementType.declaration.qualifiedName?.asString()

    if (!targetElementType.isMarkedNullable) {
        val expectedArrayName = targetElementName?.let { primitiveArrayByElement[it] }
        if (expectedArrayName != null) return sourceName == expectedArrayName
    }

    if (sourceName == "kotlin.Array") {
        val sourceElementType =
            sourceType.arguments
                .firstOrNull()
                ?.type
                ?.resolve()
                ?: return false
        return isTypeCompatible(targetElementType, sourceElementType)
    }

    return false
}

/**
 * Check if two types are compatible for property matching.
 * This includes:
 * - Direct assignability (normal cases)
 * - Both are type parameters with the same name (generic cases)
 */
private fun isTypeCompatible(
    targetType: KSType,
    sourceType: KSType,
): Boolean {
    // Check direct assignability first
    if (targetType.isAssignableFrom(sourceType)) {
        return true
    }

    // Check if both are type parameters with the same name
    val targetDecl = targetType.declaration
    val sourceDecl = sourceType.declaration
    if (targetDecl is KSTypeParameter && sourceDecl is KSTypeParameter) {
        return targetDecl.name.asString() == sourceDecl.name.asString()
    }

    return false
}
