package me.tbsten.cream.ksp.core.common

import com.google.devtools.ksp.symbol.KSClassDeclaration

/**
 * Render the canonical KDoc for a cream-generated function.
 *
 * Rendered sections, in order:
 * 1. `(Auto generate by @[Annotation] of [Target])` header
 * 2. [autoDescription] (one-liner like `Source -> Target copy function.`)
 * 3. [GenerateSourceAnnotation.kdocDescription] (user-provided, optional)
 * 4. [autoExamples] (one or more `# Example: ...` sections from cream)
 * 5. [GenerateSourceAnnotation.kdocExamples] (user-provided, optional, rendered verbatim)
 * 6. `@see` references
 *
 * Each callsite supplies the auto description and auto examples as separate blocks.
 * Both [autoDescription] and [autoExamples] must NOT end with a trailing blank line —
 * this helper inserts separators between sections itself. `appendExample` already
 * ends with a blank line, so emitting one or more `appendExample(...)` calls inside
 * [autoExamples] satisfies that.
 */
internal fun Appendable.appendAutoGeneratedFunctionKDoc(
    generateSourceAnnotation: GenerateSourceAnnotation,
    seeClasses: List<KSClassDeclaration>,
    autoDescription: KDocWriter.() -> Unit,
    autoExamples: KDocWriter.() -> Unit,
) {
    appendLine("/**")
    appendLine(" * (${autoGenerateKDoc(generateSourceAnnotation)})")
    appendLine(" * ")

    val writer = KDocWriter(" * ", this)
    writer.autoDescription()
    writer.appendLine()

    writer.appendUserKDocBlock(generateSourceAnnotation.kdocDescription)

    writer.autoExamples()

    generateSourceAnnotation.kdocExamples.forEach { example ->
        writer.appendUserKDocBlock(example)
    }

    appendLine(" * ")
    seeClasses.forEach {
        appendLine(" * @see ${it.underPackageName}")
    }
    appendLine(" */")
}

internal class KDocWriter(
    private val prefix: String,
    private val writer: Appendable,
) {
    fun appendLine(value: String = "") {
        value.split("\n").forEach { line ->
            writer.appendLine("${prefix}$line")
        }
    }
}

internal fun KDocWriter.appendExample(
    title: String,
    content: String,
) {
    appendLine("# $title")
    appendLine()
    appendLine("```kt")
    appendLine(content.trimIndent())
    appendLine("```")
    appendLine()
}

/**
 * Render a user-provided KDoc block (description or single example).
 *
 * Applies `trimIndent`, drops leading/trailing blank lines, then writes each remaining
 * line prefixed by the writer's KDoc marker and finishes with a single blank line so
 * the next block is visually separated. No-op when [content] is blank.
 */
private fun KDocWriter.appendUserKDocBlock(content: String) {
    val cleaned =
        content
            .trimIndent()
            .lines()
            .dropWhile { it.isBlank() }
            .dropLastWhile { it.isBlank() }
            .joinToString("\n")
    if (cleaned.isEmpty()) return
    appendLine(cleaned)
    appendLine()
}

private fun autoGenerateKDoc(generateSourceAnnotation: GenerateSourceAnnotation): String =
    buildString {
        append("Auto generate by @[")
        append(generateSourceAnnotation.annotationSimpleName)
        append("] annotation of [")
        append(generateSourceAnnotation.annotatedDeclaration.underPackageName)
        append("]")
    }
