package me.tbsten.cream.ksp.core.combineFun

import com.google.devtools.ksp.getConstructors
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSDeclaration
import com.google.devtools.ksp.symbol.KSTypeParameter
import me.tbsten.cream.ksp.core.common.GenerateSourceAnnotation
import me.tbsten.cream.ksp.core.common.appendAutoGeneratedFunctionKDoc
import me.tbsten.cream.ksp.core.common.appendConstructorCallBody
import me.tbsten.cream.ksp.core.common.appendExample
import me.tbsten.cream.ksp.core.common.appendSourceClassWithTypeArgs
import me.tbsten.cream.ksp.core.common.appendTargetClassWithTypeArgs
import me.tbsten.cream.ksp.core.common.appendTypeParameterList
import me.tbsten.cream.ksp.core.common.appendWhereClause
import me.tbsten.cream.ksp.core.common.deprecatedAnnotationLine
import me.tbsten.cream.ksp.core.common.findMatchedProperty
import me.tbsten.cream.ksp.core.common.fullName
import me.tbsten.cream.ksp.core.common.getCopyFunctionTypeParameters
import me.tbsten.cream.ksp.core.common.isExcludedFromCopy
import me.tbsten.cream.ksp.core.common.resolveConstructorParamTypeParameter
import me.tbsten.cream.ksp.core.common.resolveFunName
import me.tbsten.cream.ksp.core.common.toModifierString
import me.tbsten.cream.ksp.core.common.underPackageName
import me.tbsten.cream.ksp.core.common.warnIfTargetExcludeHasNoEffect
import me.tbsten.cream.ksp.options.CreamOptions
import me.tbsten.cream.ksp.util.escapeKotlinIdentifier
import me.tbsten.cream.ksp.util.ksp.asString
import java.io.BufferedWriter

context(options: CreamOptions, logger: KSPLogger)
internal fun BufferedWriter.appendCombineToClassFunction(
    primarySource: KSClassDeclaration,
    otherSources: List<KSClassDeclaration>,
    targetClass: KSClassDeclaration,
    generateSourceAnnotation: GenerateSourceAnnotation,
    omitPackages: List<String>,
    annotated: KSDeclaration = primarySource,
) {
    val allSources = listOf(primarySource) + otherSources

    targetClass.getConstructors().forEach { constructor ->
        val typeParameters =
            getCopyFunctionTypeParameters(
                sourceClass = primarySource,
                targetConstructor = constructor,
            )

        // Generate copy function
        val funName =
            resolveFunName(
                funNameTemplate = generateSourceAnnotation.funNameTemplate,
                source = primarySource,
                target = targetClass,
                options = options,
            )

        // A ctor param is REQUIRED when it does NOT receive a `= ...` default in the emitted
        // signature: either no source supplies its value, or it is @Exclude-marked in any source.
        // This mirrors the matched/excluded logic in the parameter loop below.
        val requiredCtorParamNames =
            constructor.parameters
                .filter { parameter ->
                    val matched =
                        allSources.any { source ->
                            parameter.findMatchedProperty(source, generateSourceAnnotation) != null
                        }
                    val excluded =
                        allSources.any { source ->
                            parameter
                                .findMatchedProperty(source, generateSourceAnnotation)
                                ?.let { property -> parameter.isExcludedFromCopy(property, source, generateSourceAnnotation) }
                                ?: false
                        }
                    !matched || excluded
                }.map { it.name!!.asString() }

        appendCombineToClassKDoc(allSources, targetClass, generateSourceAnnotation, annotated, funName, requiredCtorParamNames)

        deprecatedAnnotationLine(allSources)?.let { appendLine(it) }

        append("${generateSourceAnnotation.visibility.toModifierString(targetClass)} fun ")
        appendTypeParameterList(typeParameters, omitPackages)
        append(" ")
        appendSourceClassWithTypeArgs(primarySource, targetClass, typeParameters)
        append(".")
        append("$funName(")
        appendLine()

        // Add parameters for other source classes
        otherSources.forEach { otherSource ->
            val paramName = otherSource.underPackageName.replaceFirstChar { it.lowercase() }
            append("    $paramName: ${otherSource.fullName}")

            // Add type parameters if the source class has them
            // Map type parameter names to ensure consistency across all sources and target
            if (otherSource.typeParameters.isNotEmpty()) {
                append("<")
                append(
                    otherSource.typeParameters.joinToString(", ") { typeParam ->
                        // Find the mapped type parameter name in the typeParameters map
                        // This ensures all sources and target use the same type parameter names
                        typeParameters.entries
                            .find { (_, param) ->
                                param.source?.name?.asString() == typeParam.name.asString() ||
                                    param.target?.name?.asString() == typeParam.name.asString()
                            }?.key ?: typeParam.name.asString()
                    },
                )
                append(">")
            }

            append(",")
            appendLine()
        }

        // Add parameters for constructor
        constructor.parameters.forEach { parameter ->
            val paramName = parameter.name!!.asString()
            val paramType =
                parameter.type
                    .resolve()
                    .asString(
                        omitPackages = omitPackages,
                        typeParameterToString = {
                            resolveConstructorParamTypeParameter(
                                it.declaration as KSTypeParameter,
                                primarySource,
                                targetClass,
                                typeParameters,
                            )
                        },
                    )
            val modifiers = if (parameter.isVararg) "vararg " else ""
            append("    $modifiers${paramName.escapeKotlinIdentifier()}: $paramType")

            // Try to find matching property in any of the source classes
            // Use asReversed() to prioritize later source classes when properties overlap
            val matchedSourceAndProperty =
                allSources.asReversed().firstNotNullOfOrNull { source ->
                    parameter
                        .findMatchedProperty(source, generateSourceAnnotation)
                        ?.let { property -> source to property }
                }

            // Suppress the auto-copy default when the matched property is @Exclude-marked in ANY
            // contributing source — not only the "winning" source that supplies the value. With
            // overlapping property names the winner differs per generated function, so checking
            // only the winner would make an explicit @CombineTo.Exclude silently ineffective in
            // some generated functions.
            val excluded =
                allSources.any { source ->
                    parameter
                        .findMatchedProperty(source, generateSourceAnnotation)
                        ?.let { property -> parameter.isExcludedFromCopy(property, source, generateSourceAnnotation) }
                        ?: false
                }

            if (matchedSourceAndProperty != null) {
                val (matchedSource, matchedProperty) = matchedSourceAndProperty
                if (!excluded) {
                    if (matchedSource == primarySource) {
                        append(" = this.${matchedProperty.simpleName.asString().escapeKotlinIdentifier()}")
                    } else {
                        val sourceParamName = matchedSource.simpleName.asString().replaceFirstChar { it.lowercase() }
                        append(" = $sourceParamName.${matchedProperty.simpleName.asString().escapeKotlinIdentifier()}")
                    }
                }
            } else {
                parameter.warnIfTargetExcludeHasNoEffect(null, generateSourceAnnotation, logger)
            }

            append(",\n")
        }
        append(") : ")
        appendTargetClassWithTypeArgs(primarySource, targetClass, typeParameters)
        appendWhereClause(typeParameters, omitPackages)
        appendConstructorCallBody(targetClass, constructor)
    }
}

private fun BufferedWriter.appendCombineToClassKDoc(
    sources: List<KSClassDeclaration>,
    target: KSClassDeclaration,
    generateSourceAnnotation: GenerateSourceAnnotation,
    annotated: KSDeclaration,
    funName: String,
    requiredCtorParamNames: List<String>,
) {
    val requiredArgs = requiredCtorParamNames.map { "$it = $it" }
    appendAutoGeneratedFunctionKDoc(
        generateSourceAnnotation = generateSourceAnnotation,
        annotated = annotated,
        seeClasses = sources + target,
        autoDescription = {
            appendCombineAutoDescription(sources, target)
        },
        autoExamples = {
            appendExample("Example: Basic", combineExampleBody(sources, funName, extraArgs = requiredArgs))
            appendExample(
                "Example: Override property values",
                combineExampleBody(sources, funName, extraArgs = requiredArgs + "property = value"),
            )
        },
    )
}
