package me.tbsten.cream.ksp.core.combineFun

import com.google.devtools.ksp.getConstructors
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.google.devtools.ksp.symbol.KSTypeParameter
import me.tbsten.cream.ksp.core.common.FindMappedSourceProperty
import me.tbsten.cream.ksp.core.common.GenerateSourceAnnotation
import me.tbsten.cream.ksp.core.common.IsExcluded
import me.tbsten.cream.ksp.core.common.ValueClassConversionOutcome
import me.tbsten.cream.ksp.core.common.appendAutoGeneratedFunctionKDoc
import me.tbsten.cream.ksp.core.common.appendConstructorCallBody
import me.tbsten.cream.ksp.core.common.appendExample
import me.tbsten.cream.ksp.core.common.appendSourceClassWithTypeArgs
import me.tbsten.cream.ksp.core.common.appendTargetClassWithTypeArgs
import me.tbsten.cream.ksp.core.common.appendTypeParameterList
import me.tbsten.cream.ksp.core.common.appendWhereClause
import me.tbsten.cream.ksp.core.common.defaultValueExpression
import me.tbsten.cream.ksp.core.common.deprecatedAnnotationLine
import me.tbsten.cream.ksp.core.common.findMatchedProperty
import me.tbsten.cream.ksp.core.common.findValueClassConversion
import me.tbsten.cream.ksp.core.common.findValueClassConversionOutcome
import me.tbsten.cream.ksp.core.common.fullName
import me.tbsten.cream.ksp.core.common.getCopyFunctionTypeParameters
import me.tbsten.cream.ksp.core.common.isExcludedFromCopy
import me.tbsten.cream.ksp.core.common.resolveConstructorParamTypeParameter
import me.tbsten.cream.ksp.core.common.resolveFunName
import me.tbsten.cream.ksp.core.common.toModifierString
import me.tbsten.cream.ksp.core.common.underPackageName
import me.tbsten.cream.ksp.core.common.warnIfTargetExcludeHasNoEffect
import me.tbsten.cream.ksp.options.CreamOptions
import me.tbsten.cream.ksp.util.escapeKotlinIdentifier
import me.tbsten.cream.ksp.util.ksp.asString

context(options: CreamOptions, logger: KSPLogger)
internal fun Appendable.appendCombineToClassFunction(
    primarySource: KSClassDeclaration,
    otherSources: List<KSClassDeclaration>,
    targetClass: KSClassDeclaration,
    generateSourceAnnotation: GenerateSourceAnnotation,
    findMappedSourceProperty: FindMappedSourceProperty,
    isExcluded: IsExcluded,
    omitPackages: List<String>,
) {
    val allSources = listOf(primarySource) + otherSources

    targetClass.getConstructors().forEach { constructor ->
        val typeParameters =
            getCopyFunctionTypeParameters(
                sourceClass = primarySource,
                targetConstructor = constructor,
            )

        // Generate copy function
        val funName =
            resolveFunName(
                funNameTemplate = generateSourceAnnotation.funNameTemplate,
                source = primarySource,
                target = targetClass,
                options = options,
            )

        // A ctor param is REQUIRED when it does NOT receive a `= ...` default in the emitted
        // signature: no source supplies its value (neither a match nor a value-class conversion),
        // or it is @Exclude-marked in any source. Mirrors the parameter loop below.
        val requiredCtorParamNames =
            constructor.parameters
                .filter { parameter ->
                    val matched =
                        allSources.any { source ->
                            parameter.findMatchedProperty(source, findMappedSourceProperty) != null
                        }
                    if (matched) {
                        allSources.any { source ->
                            parameter
                                .findMatchedProperty(source, findMappedSourceProperty)
                                ?.let { property -> parameter.isExcludedFromCopy(property, source, isExcluded) }
                                ?: false
                        }
                    } else {
                        val conversions =
                            allSources.mapNotNull { source ->
                                parameter
                                    .findValueClassConversion(source, findMappedSourceProperty)
                                    ?.let { conversion -> source to conversion }
                            }
                        conversions.isEmpty() ||
                            conversions.any { (source, conversion) ->
                                parameter.isExcludedFromCopy(conversion.sourceProperty, source, isExcluded)
                            }
                    }
                }.map { it.name!!.asString() }

        appendCombineToClassKDoc(allSources, targetClass, generateSourceAnnotation, funName, requiredCtorParamNames)

        deprecatedAnnotationLine(allSources)?.let { appendLine(it) }

        append("${generateSourceAnnotation.visibility.toModifierString(targetClass)} fun ")
        appendTypeParameterList(typeParameters, omitPackages)
        append(" ")
        appendSourceClassWithTypeArgs(primarySource, targetClass, typeParameters)
        append(".")
        append("$funName(")
        appendLine()

        // Add parameters for other source classes
        otherSources.forEach { otherSource ->
            val paramName = otherSource.underPackageName.replaceFirstChar { it.lowercase() }
            append("    $paramName: ${otherSource.fullName}")

            // Add type parameters if the source class has them
            // Map type parameter names to ensure consistency across all sources and target
            if (otherSource.typeParameters.isNotEmpty()) {
                append("<")
                append(
                    otherSource.typeParameters.joinToString(", ") { typeParam ->
                        // Find the mapped type parameter name in the typeParameters map
                        // This ensures all sources and target use the same type parameter names
                        typeParameters.entries
                            .find { (_, param) ->
                                param.source?.name?.asString() == typeParam.name.asString() ||
                                    param.target?.name?.asString() == typeParam.name.asString()
                            }?.key ?: typeParam.name.asString()
                    },
                )
                append(">")
            }

            append(",")
            appendLine()
        }

        // One renderer for both the parameter type and any constructor call in its default, so
        // the two can never disagree on omitted packages / type parameters.
        val renderType: (KSType) -> String = { type ->
            type.asString(
                omitPackages = omitPackages,
                typeParameterToString = {
                    resolveConstructorParamTypeParameter(
                        it.declaration as KSTypeParameter,
                        primarySource,
                        targetClass,
                        typeParameters,
                    )
                },
            )
        }

        // Add parameters for constructor
        constructor.parameters.forEach { parameter ->
            val paramName = parameter.name!!.asString()
            val paramType = renderType(parameter.type.resolve())
            val modifiers = if (parameter.isVararg) "vararg " else ""
            append("    $modifiers${paramName.escapeKotlinIdentifier()}: $paramType")

            // Try to find matching property in any of the source classes
            // Use asReversed() to prioritize later source classes when properties overlap
            val matchedSourceAndProperty =
                allSources.asReversed().firstNotNullOfOrNull { source ->
                    parameter
                        .findMatchedProperty(source, findMappedSourceProperty)
                        ?.let { property -> source to property }
                }

            // Suppress the auto-copy default when the matched property is @Exclude-marked in ANY
            // contributing source — not only the "winning" source that supplies the value. With
            // overlapping property names the winner differs per generated function, so checking
            // only the winner would make an explicit @CombineTo.Exclude silently ineffective in
            // some generated functions.
            val excluded =
                allSources.any { source ->
                    parameter
                        .findMatchedProperty(source, findMappedSourceProperty)
                        ?.let { property -> parameter.isExcludedFromCopy(property, source, isExcluded) }
                        ?: false
                }

            if (matchedSourceAndProperty != null) {
                val (matchedSource, matchedProperty) = matchedSourceAndProperty
                if (!excluded) {
                    val qualifier = matchedSource.defaultValueQualifier(primarySource)
                    append(" = $qualifier.${matchedProperty.simpleName.asString().escapeKotlinIdentifier()}")
                }
            } else {
                // No match in any source: a value-class conversion may still supply a default.
                // Same asReversed() priority as above, so later sources win.
                val conversionOutcomes =
                    allSources.asReversed().map { source ->
                        source to parameter.findValueClassConversionOutcome(source, findMappedSourceProperty)
                    }
                val convertedSourceAndConversion =
                    conversionOutcomes.firstNotNullOfOrNull { (source, outcome) ->
                        (outcome as? ValueClassConversionOutcome.Applied)?.let { source to it.conversion }
                    }
                if (convertedSourceAndConversion != null) {
                    val (convertedSource, conversion) = convertedSourceAndConversion
                    // `.Exclude` in ANY contributing source wins, as for matched properties.
                    val conversionExcluded =
                        allSources.any { source ->
                            parameter
                                .findValueClassConversion(source, findMappedSourceProperty)
                                ?.let { c -> parameter.isExcludedFromCopy(c.sourceProperty, source, isExcluded) }
                                ?: false
                        }
                    if (!conversionExcluded) {
                        val qualifier = convertedSource.defaultValueQualifier(primarySource)
                        val sourceAccess =
                            "$qualifier.${conversion.sourceProperty.simpleName.asString().escapeKotlinIdentifier()}"
                        append(" = ${conversion.defaultValueExpression(sourceAccess, renderType)}")
                    }
                } else {
                    // Warn once, highest-priority source first, unless `@Exclude` opted out.
                    conversionOutcomes
                        .firstNotNullOfOrNull { (source, outcome) ->
                            (outcome as? ValueClassConversionOutcome.NearMiss)?.let { source to it }
                        }?.let { (source, nearMiss) ->
                            if (!parameter.isExcludedFromCopy(nearMiss.candidate, source, isExcluded)) {
                                logger.warn(nearMiss.message, parameter)
                            }
                        }
                }
                parameter.warnIfTargetExcludeHasNoEffect(
                    hasCandidateDefault = convertedSourceAndConversion != null,
                    generateSourceAnnotation = generateSourceAnnotation,
                    logger = logger,
                )
            }

            append(",\n")
        }
        append(") : ")
        appendTargetClassWithTypeArgs(primarySource, targetClass, typeParameters)
        appendWhereClause(typeParameters, omitPackages)
        appendConstructorCallBody(targetClass, constructor)
    }
}

/** `this` for the primary source, otherwise the source's lower-camelized simple name. */
private fun KSClassDeclaration.defaultValueQualifier(primarySource: KSClassDeclaration): String =
    if (this == primarySource) "this" else simpleName.asString().replaceFirstChar { it.lowercase() }

private fun Appendable.appendCombineToClassKDoc(
    sources: List<KSClassDeclaration>,
    target: KSClassDeclaration,
    generateSourceAnnotation: GenerateSourceAnnotation,
    funName: String,
    requiredCtorParamNames: List<String>,
) {
    val requiredArgs = requiredCtorParamNames.map { "$it = $it" }
    appendAutoGeneratedFunctionKDoc(
        generateSourceAnnotation = generateSourceAnnotation,
        seeClasses = sources + target,
        autoDescription = {
            appendCombineAutoDescription(sources, target)
        },
        autoExamples = {
            appendExample("Example: Basic", combineExampleBody(sources, funName, extraArgs = requiredArgs))
            appendExample(
                "Example: Override property values",
                combineExampleBody(sources, funName, extraArgs = requiredArgs + "property = value"),
            )
        },
    )
}
