package me.tbsten.cream.ksp.core.combineFun

import com.google.devtools.ksp.symbol.KSClassDeclaration
import me.tbsten.cream.CopyVisibility
import me.tbsten.cream.DefaultCopyFunctionName
import me.tbsten.cream.ksp.GenerateSourceAnnotation
import me.tbsten.cream.ksp.core.common.appendAutoGeneratedFunctionKDoc
import me.tbsten.cream.ksp.core.common.appendExample
import me.tbsten.cream.ksp.core.common.fullName
import me.tbsten.cream.ksp.core.common.resolveFunName
import me.tbsten.cream.ksp.core.common.toModifierString
import me.tbsten.cream.ksp.core.common.underPackageName
import me.tbsten.cream.ksp.options.CreamOptions
import java.io.BufferedWriter

context(options: CreamOptions)
internal fun BufferedWriter.appendCombineToObjectFunction(
    primarySource: KSClassDeclaration,
    otherSources: List<KSClassDeclaration>,
    targetObject: KSClassDeclaration,
    generateSourceAnnotation: GenerateSourceAnnotation<*>,
    visibility: CopyVisibility = CopyVisibility.INHERIT,
    funNameTemplate: String = DefaultCopyFunctionName,
) {
    val allSources = listOf(primarySource) + otherSources
    val funName =
        resolveFunName(
            funNameTemplate = funNameTemplate,
            source = primarySource,
            target = targetObject,
            options = options,
        )
    appendCombineToObjectKDoc(allSources, targetObject, generateSourceAnnotation, funName)
    appendLine(
        "${visibility.toModifierString(targetObject)} fun ${primarySource.fullName}.$funName(${
            otherSources.joinToString(", ") { otherSource ->
                "${otherSource.underPackageName.replaceFirstChar { it.lowercase() }}: ${otherSource.fullName}"
            }
        }) = ${targetObject.fullName}",
    )
}

private fun BufferedWriter.appendCombineToObjectKDoc(
    sources: List<KSClassDeclaration>,
    target: KSClassDeclaration,
    generateSourceAnnotation: GenerateSourceAnnotation<*>,
    funName: String,
) {
    appendAutoGeneratedFunctionKDoc(
        generateSourceAnnotation = generateSourceAnnotation,
        seeClasses = sources + target,
        autoDescription = {
            appendCombineAutoDescription(sources, target)
        },
        autoExamples = {
            appendExample("Example: Basic", combineExampleBody(sources, funName))
        },
    )
}
