package me.tbsten.cream.ksp.core.combineFun

import com.google.devtools.ksp.symbol.KSClassDeclaration
import me.tbsten.cream.ksp.core.common.GenerateSourceAnnotation
import me.tbsten.cream.ksp.core.common.appendAutoGeneratedFunctionKDoc
import me.tbsten.cream.ksp.core.common.appendExample
import me.tbsten.cream.ksp.core.common.fullName
import me.tbsten.cream.ksp.core.common.resolveFunName
import me.tbsten.cream.ksp.core.common.toModifierString
import me.tbsten.cream.ksp.core.common.underPackageName
import me.tbsten.cream.ksp.options.CreamOptions

context(options: CreamOptions)
internal fun Appendable.appendCombineToObjectFunction(
    primarySource: KSClassDeclaration,
    otherSources: List<KSClassDeclaration>,
    targetObject: KSClassDeclaration,
    generateSourceAnnotation: GenerateSourceAnnotation,
) {
    val allSources = listOf(primarySource) + otherSources
    val funName =
        resolveFunName(
            funNameTemplate = generateSourceAnnotation.funNameTemplate,
            source = primarySource,
            target = targetObject,
            options = options,
        )
    appendCombineToObjectKDoc(allSources, targetObject, generateSourceAnnotation, funName)
    appendLine(
        "${generateSourceAnnotation.visibility.toModifierString(targetObject)} fun ${primarySource.fullName}.$funName(${
            otherSources.joinToString(", ") { otherSource ->
                "${otherSource.underPackageName.replaceFirstChar { it.lowercase() }}: ${otherSource.fullName}"
            }
        }) = ${targetObject.fullName}",
    )
}

private fun Appendable.appendCombineToObjectKDoc(
    sources: List<KSClassDeclaration>,
    target: KSClassDeclaration,
    generateSourceAnnotation: GenerateSourceAnnotation,
    funName: String,
) {
    appendAutoGeneratedFunctionKDoc(
        generateSourceAnnotation = generateSourceAnnotation,
        seeClasses = sources + target,
        autoDescription = {
            appendCombineAutoDescription(sources, target)
        },
        autoExamples = {
            appendExample("Example: Basic", combineExampleBody(sources, funName))
        },
    )
}
