package me.tbsten.cream.ksp.core.sealedCopy

import com.google.devtools.ksp.symbol.KSClassDeclaration
import me.tbsten.cream.ksp.core.common.GenerateSourceAnnotation
import me.tbsten.cream.ksp.core.common.appendAutoGeneratedFunctionKDoc
import me.tbsten.cream.ksp.core.common.appendExample
import java.io.BufferedWriter

internal fun BufferedWriter.appendSealedCopyKDoc(
    sealedClass: KSClassDeclaration,
    funName: String,
    classifiedLeaves: List<SealedCopyLeaf>,
    nullable: Boolean,
    generateSourceAnnotation: GenerateSourceAnnotation.SealedCopy,
    requiredParamNames: List<String>,
) {
    val sealedSimple = sealedClass.simpleName.asString()
    val resultType = if (nullable) "$sealedSimple?" else sealedSimple
    val requiredArgs = requiredParamNames.joinToString(", ") { "$it = $it" }
    val basicCall = if (requiredArgs.isEmpty()) "" else requiredArgs
    val overrideCall =
        if (requiredArgs.isEmpty()) "property = value" else "$requiredArgs, property = value"
    appendAutoGeneratedFunctionKDoc(
        generateSourceAnnotation = generateSourceAnnotation,
        seeClasses = listOf(sealedClass) + classifiedLeaves.map { it.declaration },
        autoDescription = {
            appendLine("Type-preserving $sealedSimple.$funName generated by @SealedCopy.")
            appendLine()
            appendLine("Updates shared abstract properties and dispatches to each subtype's copy.")
        },
        autoExamples = {
            appendExample(
                "Example: Basic",
                """
                val state: $sealedSimple = /* one of the subtypes */
                val updated: $resultType = state.$funName($basicCall)
                """.trimIndent(),
            )

            appendExample(
                "Example: Override property values",
                """
                val state: $sealedSimple = /* one of the subtypes */
                val updated: $resultType = state.$funName($overrideCall)
                """.trimIndent(),
            )
        },
    )
}
