name: Deploy Option Builder
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-to-web:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: pages-deploy
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java for Gradle
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - run: mkdir ./public

      - name: Build publish js contents
        run: ./gradlew :optionBuilder:webApp:jsBrowserDistribution
      - run: cp -r ./optionBuilder/webApp/build/dist/js/productionExecutable/* ./public/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: ./option-builder
